FROM python:3.9-slim-buster

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY mongo_streaming/mongo_streaming.py .

CMD ["python", "-u", "mongo_streaming.py"]