FROM python:3.9-slim-buster

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY postgres_streaming/postgres_streaming.py .

CMD ["python", "-u", "postgres_streaming.py"] 